---
helmDefaults:
  atomic: false
  force: false
  timeout: 480
  wait: true

releases:
- name: jenkins
  chart: jenkins/jenkins
  version: 3.3.18
  namespace: jenkins
  values: ["../config/default/jenkins.yaml"]
  set:
  - name: namespace
    value: jenkins
